# -*- coding: utf-8 -*-
"""Python_module_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OtxV_Wr8G5cDyQB3GC3JVVZsPZsfzPk9
"""

# HackerRank Python Assignment Solutions

## Question 1: Hello World
print("Hello, World!")

## Question 2: If-Else

n = int(input())

if n % 2 != 0:
    print("Weird")
elif 2 <= n <= 5:
    print("Not Weird")
elif 6 <= n <= 20:
    print("Weird")
else:
    print("Not Weird")

## Question 3: Arithmetic Operators

a = int(input())
b = int(input())

print(a + b)
print(a - b)
print(a * b)

## Question 4: Division

a = int(input())
b = int(input())

print(a // b)
print(a / b)

## Question 5: Loops

n = int(input())

for i in range(n):
    print(i ** 2)

## Question 6: Leap Year

def is_leap(year):
    return year % 400 == 0 or (year % 4 == 0 and year % 100 != 0)

year = int(input())
print(is_leap(year))

## Question 7: Print Function

n = int(input())

for i in range(1, n + 1):
    print(i, end="")

## Question 8: List Comprehensions


x = int(input())
y = int(input())
z = int(input())
n = int(input())

result = [[i, j, k]
          for i in range(x + 1)
          for j in range(y + 1)
          for k in range(z + 1)
          if i + j + k != n]

print(result)

## Question 9: Runner-Up Score


n = int(input())
arr = list(map(int, input().split()))

print(sorted(set(arr))[-2])

## Question 10: Nested Lists
students = []

for _ in range(int(input())):
    name = input()
    score = float(input())
    students.append([name, score])

scores = sorted(set(score for name, score in students))
second_lowest = scores[1]

names = sorted(name for name, score in students if score == second_lowest)

for name in names:
    print(name)

## Question 11: Finding the Percentage


n = int(input())
student_marks = {}

for _ in range(n):
    name, *line = input().split()
    scores = list(map(float, line))
    student_marks[name] = scores

query_name = input()

average = sum(student_marks[query_name]) / len(student_marks[query_name])
print("{:.2f}".format(average))

## Question 12: Lists


N = int(input())
lst = []

for _ in range(N):
    command = input().split()

    if command[0] == "insert":
        lst.insert(int(command[1]), int(command[2]))
    elif command[0] == "print":
        print(lst)
    elif command[0] == "remove":
        lst.remove(int(command[1]))
    elif command[0] == "append":
        lst.append(int(command[1]))
    elif command[0] == "sort":
        lst.sort()
    elif command[0] == "pop":
        lst.pop()
    elif command[0] == "reverse":
        lst.reverse()

## Question 13: Tuples

n = int(input())
integer_list = tuple(map(int, input().split()))
print(hash(integer_list))

## Question 14: sWAP cASE

def swap_case(s):
    return s.swapcase()

print(swap_case(input()))

## Question 15: String Split and Join

def split_and_join(line):
    return "-".join(line.split())

print(split_and_join(input()))

## Question 16: What's Your Name?


first = input()
last = input()

print(f"Hello {first} {last}! You just delved into python.")

## Question 17: Mutations

def mutate_string(string, position, character):
    return string[:position] + character + string[position+1:]

s = input()
i, c = input().split()

print(mutate_string(s, int(i), c))

## Question 18: Find a String

def count_substring(string, sub_string):
    count = 0

    for i in range(len(string) - len(sub_string) + 1):
        if string[i:i+len(sub_string)] == sub_string:
            count += 1

    return count

string = input()
sub_string = input()

print(count_substring(string, sub_string))

## Question 19: String Validators

s = input()

print(any(c.isalnum() for c in s))
print(any(c.isalpha() for c in s))
print(any(c.isdigit() for c in s))
print(any(c.islower() for c in s))
print(any(c.isupper() for c in s))

## Question 20: Text Alignment
thickness = int(input())
c = 'H'

for i in range(thickness):
    print((c*i).rjust(thickness-1)+c+(c*i).ljust(thickness-1))

for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))

for i in range((thickness+1)//2):
    print((c*thickness*5).center(thickness*6))

for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))

for i in range(thickness):
    print(((c*(thickness-i-1)).rjust(thickness)+c+(c*(thickness-i-1)).ljust(thickness)).rjust(thickness*6))

## Question 21: Text Wrap
import textwrap

def wrap(string, max_width):
    return textwrap.fill(string, max_width)

string = input()
max_width = int(input())

print(wrap(string, max_width))

## Question 22: Designer Door Mat
n, m = map(int, input().split())

for i in range(1, n, 2):
    print(('.|.' * i).center(m, '-'))

print('WELCOME'.center(m, '-'))

for i in range(n - 2, -1, -2):
    print(('.|.' * i).center(m, '-'))

## Question 23: String Formatting
def print_formatted(number):
    width = len(bin(number)) - 2

    for i in range(1, number + 1):
        print(
            str(i).rjust(width),
            oct(i)[2:].rjust(width),
            hex(i)[2:].upper().rjust(width),
            bin(i)[2:].rjust(width)
        )

n = int(input())
print_formatted(n)

## Question 24: Alphabet Rangoli
def print_rangoli(size):
    import string

    alpha = string.ascii_lowercase
    width = 4 * size - 3

    for i in range(size - 1, -size, -1):
        x = abs(i)
        row = "-".join(alpha[size-1:x:-1] + alpha[x:size])
        print(row.center(width, "-"))

n = int(input())
print_rangoli(n)

## Question 25: Capitalize
def solve(s):
    return ' '.join(word.capitalize() for word in s.split(' '))

s = input()
print(solve(s))

## Question 26: The Minion Game
def minion_game(string):
    vowels = "AEIOU"
    kevin = 0
    stuart = 0
    n = len(string)

    for i in range(n):
        if string[i] in vowels:
            kevin += n - i
        else:
            stuart += n - i

    if kevin > stuart:
        print("Kevin", kevin)
    elif stuart > kevin:
        print("Stuart", stuart)
    else:
        print("Draw")

s = input()
minion_game(s)

## Question 27: Merge the Tools
def merge_the_tools(string, k):
    for i in range(0, len(string), k):
        part = string[i:i+k]

        unique = ""
        for char in part:
            if char not in unique:
                unique += char

        print(unique)

string = input()
k = int(input())

merge_the_tools(string, k)

## Question 28: Day 0 - Hello World
input_string = input()

print("Hello, World.")
print(input_string)

## Question 29: Day 2 - Operators
meal_cost = float(input())
tip_percent = int(input())
tax_percent = int(input())

total_cost = meal_cost + (meal_cost * tip_percent / 100) + (meal_cost * tax_percent / 100)

print(round(total_cost))

## Question 30: Day 3 - Intro to Conditional Statements
N = int(input())

if N % 2 != 0:
    print("Weird")
elif 2 <= N <= 5:
    print("Not Weird")
elif 6 <= N <= 20:
    print("Weird")
else:
    print("Not Weird")

## Question 31: Day 4 - Class vs Instance
class Person:
    def __init__(self, initialAge):
        if initialAge < 0:
            print("Age is not valid, setting age to 0.")
            self.age = 0
        else:
            self.age = initialAge

    def amIOld(self):
        if self.age < 13:
            print("You are young.")
        elif self.age < 18:
            print("You are a teenager.")
        else:
            print("You are old.")

    def yearPasses(self):
        self.age += 1

## Question 32: Day 5 - Loops
n = int(input())

for i in range(1, 11):
    print(f"{n} x {i} = {n*i}")

## Question 33: Day 6 - Let's Review
t = int(input())

for _ in range(t):
    s = input()

    even = s[::2]
    odd = s[1::2]

    print(even, odd)

## Question 34: Day 7 - Arrays
n = int(input())
arr = list(map(int, input().split()))

print(*arr[::-1])



## Question 35: Day 8 - Dictionaries and Maps
n = int(input())

phone_book = {}

for _ in range(n):
    name, number = input().split()
    phone_book[name] = number

q = int(input())  # number of queries

for _ in range(q):
    query = input()

    if query in phone_book:
        print(query + "=" + phone_book[query])
    else:
        print("Not found")